# Your Name or Company
title: Lady Bee Mixology

# Description of your website. This is used for social sharing.
description:  The Home of Lady Bee Mixology Gourmet Cocktails

# A brief blurb about yourself
content: Lady Bee Mixology is a vibrant Jamaican cocktail brand redefining the art of ready‑to‑drink beverages with bold creativity and authentic island flavour.
# Add your social links
social:
  - platform: instagram
    url: https://instagram.com/ladybeemixology
 # - platform: facebook
 #   url: https://facebook.com/brianmaierjr
 # - platform: twitter
 #   url: https://twitter.com/brianmaierjr
 # - platform: linkedin
 #S   url: brianmaierjr

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
